### PR TITLE
Grunt build, removed console.logs

### PR DESCRIPTION
**Pull request by Hyzual**
Removes leftover `console.log`s in #201

### CODE REVIEW

**Comment by tsquillario** [comment]
I'm getting an error on this one: Failed to set the 'volume' property on 'HTMLMediaElement': The provided double value is non-finite.

**Comment by Hyzual** [comment]
Okay, I'll look into it

**Comment by tsquillario** [comment]
Seemed to be an issue with one of the previous values saved in localstorage. If launching incognito or clearing them it works fine. Nothing to worry about.

**Comment by Hyzual** [comment]
There was still kind of a rounding "issue", so I've reused the `Math.round()` code you had.
Also, I've noticed while using it that pressing "space" (or any other global shortcut) while on the search input triggers the pause / nextSong, etc. when they should not. This wasn't a problem before v4.4.3.
Those two issues should be fixed on my develop branch, I'm taking the time to test them this time before doing a pull request :). I'll probably make it in a day or two.

**Pull request merged**
