### PR TITLE
Fix flac playing

### PR DESCRIPTION
**Pull request by d3m3vilurr**

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
it would resolve #225

**Comment by d3m3vilurr** [comment]
it couldn't be a shot. i found another unplayable sound in the firefox.

**Comment by klausweiss** [comment]
I confirm that with the changes flacs are working fine in Firefox 81.0. I haven't had a problem with them yet.

**Comment by pR0Ps** [comment]
I did a slight refactor to clean up some repeated logic but otherwise this looks good. Thanks!

**Pull request merged**
